
//It has to be an "async" function in order to use the 'await' function, which is used to wait for the xml data to be fully loaded each time.
async function searchProduct() {
    codeInput = document.getElementById("productCode").value.trim();
    //get the xml to be loaded into the getPage cariable and then load all of it into 'data' as raw text
    rawXML = await fetch('products.xml');
    data = await rawXML.text();
    //Code example seen at:
    //www.w3schools.com. (n.d.). XML Parser. [online] Available at: https://www.w3schools.com/xml/xml_parser.asp.
    //Parcer produces a new xml document from the text in "data" so it can be manipulated on the js
    parserXML = new DOMParser();    
    xmlDoc = parserXML.parseFromString(data,"application/xml");
    
    
    codePath = `/products/product[@code='${codeInput}']`;
    //Sets the xPath of the inputed code 
    result = xmlDoc.evaluate(codePath,xmlDoc,null,XPathResult.FIRST_ORDERED_NODE_TYPE, null)
    //Evaluate function seen at:
    //www.w3schools.com. (n.d.). XPath Examples. [online] Available at: https://www.w3schools.com/xml/xpath_examples.asp.
    //Evaluate is used to select the node using the path generated by the user 


    productInfo = result.singleNodeValue;
    //returns only one node from all the available values (in case there is more, which should not happen since every product in the xml has a different code)

    showSection =  document.getElementById("resultSection");
    //Define the section div to be able to display the information there 

    if (productInfo != null){
        //gets the info from the node and sets variables with the different data
        theName = productInfo.getElementsByTagName("name")[0].textContent;
        stockStatus = productInfo.getElementsByTagName("stockStatus")[0].textContent;
        unitPrice = productInfo.getElementsByTagName("unitPrice")[0].textContent;
        ratings = productInfo.getElementsByTagName("ratings")[0].textContent;
        image = productInfo.getElementsByTagName("image")[0].textContent;

        //Display results
       showSection.innerHTML = `
            <img src="${image}" alt="${theName}" style="width: 150px; height: auto; margin-bottom: 15px;">
            <p>Product: ${theName}</p>
            <p>Stock Status: ${stockStatus}</p>
            <p>Unit Price: €${unitPrice}</p>
            <p>Ratings: ${ratings}</p>
            <button class="toProds-button" onclick="orderProduct()">Order!</button>
        `;
    } else {
        alert(codeInput + " not found.");
        showSection.innerHTML = "";
        //Reset values on page
    }
}


//Buy button

function orderProduct(){
    
    alert("Your order as been placed!");
}
